### ISSUE TITLE
Compare performance with C# wrapper around CRoaring

### ISSUE THREAD

**Issue by lemire** [Tornhoof/RoaringBitmap#1]
It might be interesting to compare performance...

https://github.com/RogueException/CRoaring.Net

**Comment by Tornhoof** [comment]
Great idea @lemire 
I did a quick port of the benchmark files to CRoaring.Net by @RogueException.
Summary of results:

For the actual bitwise operations the wrapper is between **30% and 120% faster** than the managed .NET implementation.

The main downside is the iteration test, where the container is iterated and all the values are returned. It is actually **25 times slower** than the .NET implementation. I guess this is due to the P/Invoke overhead for each step in the iteration.

So for iteration a better way is necessary, maybe a bulk iterator, i.e. return 100 values instead of one and iterate over those in .NET, should reduce the overhead quite a bit.

```ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4790K CPU 4.00GHz, ProcessorCount=8
Frequency=3906251 ticks, Resolution=255.9999 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0

Type=MicroBenchmarkCensusIncome  Mode=Throughput  

```
  Method |            Median |         StdDev |  Gen 0 |  Gen 1 | Gen 2 | Bytes Allocated/Op |
-------- |------------------ |--------------- |------- |------- |------ |------------------- |
      Or |       953.9583 us |      8.5292 us |   0.42 |   0.42 |  0.59 |          61.993,21 |
     Xor |     1,774.0715 us |     85.5056 us |   0.66 |   0.91 |  1.06 |         106.532,48 |
     And |     1,031.6232 us |     29.3245 us |   0.38 |   0.53 |  0.62 |          63.245,14 |
  AndNot |     1,751.2866 us |     10.2734 us |   0.89 |   1.05 |  1.31 |         134.555,02 |
 Iterate | 2,272,767.7702 us | 21,507.9128 us | 623.00 | 330.00 | 42.00 |      25.847.734,47 |

The result of the same benchmark on the same machine for the managed .NET implementation is on the main page of the repository.

**Comment by lemire** [comment]
c.c. @RogueException

**Comment by Tornhoof** [comment]
I did a bit of further investigation into the iterator:

The slowdown is mainly due to the iterator implementation in CRoaring.NET, that one is necessary because we do not want to read all values from the iterator into our code at once. So it's not a PInvoke problem, but rather overhead of blocking collections etc.
If I replace the iterator with a simple queue based one which gets all the values into our code at once, the iterator is only twice as slow as the managed one, but the memory usage then is out of bounds ;)

roaring_iterator can't be used to do that more efficiently as it can't be paused (as soon as you return false, it will start at the beginning again).

https://github.com/RoaringBitmap/CRoaring/issues/60 apparently suggests an iterator, but for interop simple c classes are way simpler.

**Comment by RogueException** [comment]
I went with a pretty naive approach with converting the CRoaring iterator to a C# Enumerable. Likely most of that overhead comes from using an threadsafe blocking collection.

**Comment by RogueException** [comment]
Exposing an IObservable instead of an IEnumerable would be a more direct wrapper, but require the user to use something like Reactive Extensions to consume it.

**Comment by Tornhoof** [comment]
Thanks for your explanation, I'll close this issue as the benchmark results are available.
