### ISSUE TITLE
Versio 1.0 planned

### ISSUE THREAD

**Issue by nhaberl** [Tornhoof/RoaringBitmap#7]
Is there any plan to make some further tests or updates to V 1?

**Comment by Tornhoof** [comment]
Good question actually, there are/were 3 topics on my internal 1.0 roadmap:
1. Run Containers (see #4), but all my attempts to get it working in a performant way failed, so I just implemented the import/export format part.
2. Builder-style creation, like the Immutable types to reduce the memory allocations, but all my use cases basically just feature the normal bitwise operations on more or less fixed bitmaps and that's why I never really saw the need to implement them.
3. Intrinsic support, I evaluated that in branch netcoreapp2.1 late last year, but as Intrinsic support in .NET core is delayed until 3.0 (afaik), these experiments were stopped.

So at the moment there are no immediate plans to extend the functionality further.
